/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        kl: {
          'on-surface-variant': '#584237',
          'on-primary-fixed-variant': '#7a3000',
          'outline': '#8c7166',
          'error-container': '#ffdad6',
          'surface-tint': '#a04100',
          'on-surface': '#1e1b18',
          'primary-container': '#f37021',
          'on-background': '#1e1b18',
          'on-primary': '#ffffff',
          'surface-variant': '#e9e1dc',
          'surface-container-lowest': '#ffffff',
          'on-secondary-fixed-variant': '#005313',
          'surface-container-high': '#efe6e2',
          'background': '#fff8f5',
          'on-tertiary-container': '#402c00',
          'primary-fixed': '#ffdbcb',
          'outline-variant': '#e0c0b2',
          'on-primary-container': '#541f00',
          'surface-container-highest': '#e9e1dc',
          'secondary-fixed': '#94f990',
          'tertiary': '#7c5800',
          'secondary-fixed-dim': '#78dc77',
          'inverse-on-surface': '#f8efea',
          'on-error-container': '#93000a',
          'inverse-primary': '#ffb693',
          'on-primary-fixed': '#341000',
          'tertiary-fixed': '#ffdea8',
          'surface-bright': '#fff8f5',
          'surface': '#fff8f5',
          'secondary-container': '#91f78e',
          'secondary': '#006e1c',
          'on-secondary-fixed': '#002204',
          'on-error': '#ffffff',
          'primary': '#a04100',
          'on-tertiary-fixed-variant': '#5e4200',
          'surface-container-low': '#fbf2ed',
          'inverse-surface': '#34302c',
          'on-tertiary': '#ffffff',
          'tertiary-fixed-dim': '#ffba20',
          'error': '#ba1a1a',
          'surface-dim': '#e1d8d4',
          'on-secondary': '#ffffff',
          'surface-container': '#f5ece7',
          'primary-fixed-dim': '#ffb693',
          'on-secondary-container': '#00731e',
          'tertiary-container': '#c48d00',
          'on-tertiary-fixed': '#271900'
        }
      },
      spacing: {
        'kl-sm': '12px',
        'kl-margin': '32px',
        'kl-md': '24px',
        'kl-xs': '4px',
        'kl-base': '8px',
        'kl-xl': '64px',
        'kl-lg': '40px',
        'kl-gutter': '24px'
      },
      fontSize: {
        'kl-label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'kl-headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'kl-headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'kl-body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'kl-body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'kl-display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'kl-label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }]
      },
      fontFamily: {
        'kl-label-sm': ['Inter', 'sans-serif'],
        'kl-headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'kl-headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'kl-body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'kl-body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'kl-display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'kl-label-md': ['Inter', 'sans-serif']
      }
    },
  },
  plugins: [],
}
