import { useContext } from 'react'
import { BudidayaContext } from '../contexts/BudidayaContext'

export function getBudidayaTerms(farmType = 'ikan', isTanaman = false) {
  const normType = String(farmType || '').toLowerCase();

  // 1. Sektor Pertanian / Budidaya Tanaman
  if (isTanaman || normType === 'tanaman' || normType === 'budidaya-tanaman') {
    return {
      isTanaman: true,
      category: 'tanaman',
      brandName: 'AgriSmart',
      brandSub: 'Pertanian Pintar',
      brandIcon: 'eco',
      unit: 'Lahan',
      unitLower: 'lahan',
      unitCode: 'Kode Lahan',
      unitName: 'Nama Lahan',
      newUnit: 'Lahan Baru',
      addUnit: 'Tambah Lahan',
      registerUnit: 'Daftarkan Lahan',
      typeUnit: 'Jenis Lahan',
      types: [
        ['tanah', 'Tanah'],
        ['bedengan', 'Bedengan'],
        ['polybag', 'Polybag'],
        ['hidroponik', 'Hidroponik']
      ],
      selectUnit: 'Pilih Unit Lahan (Tersedia)',
      noUnitEmpty: '* Tidak ada unit lahan kosong tersedia saat ini.',
      seedTypeLabel: 'Jenis / Varietas Benih',
      seedCountLabel: 'Jumlah Tanam (Batang)',
      seedCountLabelShort: 'Jumlah Tanam',
      seedDateLabel: 'Tanggal Tanam',
      startCycleLabel: 'Mulai Siklus (Tanam)',
      startCycleAction: 'Mulai Tanam',
      emptyCyclesDesc: 'Tanam benih/bibit di lahan yang kosong untuk memulai monitoring',
      phLabel: 'pH Tanah',
      tempLabel: 'Suhu Udara',
      o2Label: 'Kelembaban Tanah',
      feedLabel: 'Pupuk & Nutrisi',
      feedLabelShort: 'Pupuk',
      feedUnit: 'Nutrisi',
      healthLabel: 'Kesehatan Tanaman',
      populationLabel: 'Kapasitas (batang)',
      populationCount: 'batang',
      populationCountTitle: 'Populasi',
      growthLabel: 'Grafik Pertumbuhan Tanaman',
      growthSub: 'Kenaikan tinggi rata-rata (cm) per minggu',
      growthUnit: 'cm',
      growthMetricLabel: 'Tinggi rata-rata',
      activeSeedLabel: 'Tanaman aktif',
      noSeedLabel: 'Belum ada tanaman',
      seedGrowthTrend: 'Tren pertumbuhan tanaman',
      envCardTitle: 'Kondisi Lahan & Tanah',
      envCardIcon: 'eco',
      envMainParamLabel: 'pH Tanah',
      envMainParamVal: '6.2',
      envMainStatus: 'Optimal',
      climateCardTitle: 'Suhu & Kelembaban Tanah',
      climateParam1Label: 'Suhu Udara',
      climateParam1Val: '26.4°C',
      climateParam2Label: 'Kelembaban Tanah',
      climateParam2Val: '65%',
      climateTrend: 'Kondisi lahan stabil',
      weatherRiskText: 'Risiko genangan',
      samplingDesc: 'Sampling dilakukan dengan mengukur tinggi sampel tanaman secara acak lalu menghitung rata-rata.',
      samplingPlaceholder: 'Contoh: Tanaman subur, tinggi merata, daun hijau segar...',
      healthDiseasePlaceholder: 'Contoh: Daun menguning, layu daun bawah...',
      weatherAdvice: 'Peringatan: Sesuaikan jadwal penyiraman jika curah hujan tinggi.',
      iconMain: 'grass',
      iconFeed: 'eco',
      iconSeed: 'spa',
      iconCycle: 'nature',
      iconUnitDefault: 'yard',
      inventoryCategories: ['Semua', 'Pupuk', 'Benih', 'Pestisida', 'Peralatan', 'Lainnya'],
      defaultInventoryCategory: 'pupuk',
      emptyInventoryDesc: 'Mulai tambahkan pupuk atau benih ke gudang Anda.',
      stockReceiveNote: 'Pupuk/nutrisi masuk',
      stockNotePlaceholder: 'Contoh: Pembelian pupuk baru, Pemupukan harian',
      statsTodayFeed: 'Total nutrisi hari ini',
      statsTemp: 'Suhu udara',
      statsO2: 'Kelembaban tanah',
      statsPH: 'Rata-rata pH tanah',
      statsTodayFeedVal: '12.4 L',
      statsTempVal: '26.4°C',
      statsO2Val: '65%',
      statsPHVal: '6.2',
      totalUnitsLabel: 'Total Lahan',
      warningLabel: 'Kelembaban Rendah (Lahan B3)',
      nextFeedLabel: 'Jadwal Pemupukan Berikutnya',
      nextFeedDetail: 'Nutrisi A cair – 45 Menit lagi',
      tempAvgLabel: 'Suhu Udara Rata-rata',
      idealConditionLabel: 'Kondisi Ideal untuk Cabai',
      mockA1Title: 'Lahan A1 - Pembesaran Cabai',
      mockA1Details: 'Usia: 45 Hari | Populasi: 2000 Batang',
      mockB3Title: 'Lahan B3 - Semai Melon',
      mockB3Details: 'Usia: 12 Hari | Populasi: 500 Batang',
      mockB3Warning: 'Kelembaban Tanah Rendah',
      alert1Title: 'Penyiraman Selesai',
      alert1Desc: 'Lahan A1 telah mencapai target kelembaban.',
      alert2Title: 'Waktunya Pemupukan',
      alert2Desc: 'Jadwal pemberian NPK untuk Lahan A2 hari ini.',
      mockKPIs: [
        { label: 'Suhu', val: '26.4°C' },
        { label: 'Kelembaban', val: '65%' },
        { label: 'pH Tanah', val: '6.2' }
      ],
      mockB3KPIs: [
        { label: 'Suhu', val: '28.1°C' },
        { label: 'Kelembaban', val: '42%', alert: true },
        { label: 'pH Tanah', val: '5.8', alert: true }
      ]
    }
  }

  // 2. Sektor Ruminansia / Ternak Sapi / Kambing / Domba
  const isRuminansia = normType === 'ruminansia' || normType === 'sapi' || normType === 'livestock' || normType === 'kambing' || normType === 'domba';
  if (isRuminansia) {
    return {
      isTanaman: false,
      category: 'livestock',
      brandName: 'AgroTernak',
      brandSub: 'Budidaya Pintar',
      brandIcon: 'agriculture',
      unit: 'Kandang',
      unitLower: 'kandang',
      unitCode: 'Kode Kandang / Pen',
      unitName: 'Nama Kandang',
      newUnit: 'Kandang Baru',
      addUnit: 'Tambah Kandang',
      registerUnit: 'Daftarkan Kandang',
      typeUnit: 'Tipe Kandang',
      types: [
        ['pen_individu', 'Pen Individu / Sekat'],
        ['koloni', 'Kandang Koloni'],
        ['terbuka', 'Kandang Terbuka / Gembala'],
        ['semi_tertutup', 'Semi Tertutup']
      ],
      selectUnit: 'Pilih Unit Kandang / Pen (Tersedia)',
      noUnitEmpty: '* Tidak ada unit kandang kosong tersedia saat ini.',
      seedTypeLabel: 'Jenis Ras / Bakalan Ternak',
      seedCountLabel: 'Jumlah Ternak (Ekor)',
      seedCountLabelShort: 'Jumlah Ternak',
      seedDateLabel: 'Tanggal Masuk / Beli',
      startCycleLabel: 'Mulai Penggemukan / Siklus Baru',
      startCycleAction: 'Mulai Penggemukan',
      emptyCyclesDesc: 'Mulai catat penggemukan atau breeding ternak pada kandang yang tersedia',
      phLabel: 'Kadar Amonia Kandang',
      tempLabel: 'Suhu Kandang',
      o2Label: 'Kelembaban Udara',
      feedLabel: 'Pakan Konsentrat & Hijauan',
      feedLabelShort: 'Pakan',
      feedUnit: 'Pakan Konsentrat',
      healthLabel: 'Kesehatan & Vaksinasi Ternak',
      populationLabel: 'Kapasitas Kandang (Ekor)',
      populationCount: 'ekor',
      populationCountTitle: 'Populasi',
      growthLabel: 'Grafik Pertumbuhan Bobot Ternak (kg)',
      growthSub: 'Kenaikan bobot rata-rata (kg) per penimbangan sampling',
      growthUnit: 'kg',
      growthMetricLabel: 'Bobot rata-rata',
      activeSeedLabel: 'Ternak aktif',
      noSeedLabel: 'Belum ada ternak terisi',
      seedGrowthTrend: 'Tren pertumbuhan bobot ternak',
      envCardTitle: 'Sanitasi & Kebersihan Kandang',
      envCardIcon: 'health_and_safety',
      envMainParamLabel: 'Kadar Amonia',
      envMainParamVal: 'Aman (0.01 ppm)',
      envMainStatus: 'Optimal',
      climateCardTitle: 'Suhu & Kelembaban Kandang',
      climateParam1Label: 'Suhu Kandang',
      climateParam1Val: '27.8°C',
      climateParam2Label: 'Kelembaban Udara',
      climateParam2Val: '60%',
      climateTrend: 'Suhu nyaman untuk ternak',
      weatherRiskText: 'Risiko suhu dingin',
      samplingDesc: 'Sampling dilakukan dengan menimbang bobot ternak secara berkala.',
      samplingPlaceholder: 'Contoh: Nafsu makan sapi tinggi, aktif bergerak, feses normal...',
      healthDiseasePlaceholder: 'Contoh: Nafsu makan turun, hidung berair, lesu...',
      weatherAdvice: 'Peringatan: Pastikan tirai kandang tertutup saat malam dingin.',
      iconMain: 'agriculture',
      iconFeed: 'restaurant',
      iconSeed: 'pets',
      iconCycle: 'inventory',
      iconUnitDefault: 'home_work',
      inventoryCategories: ['Semua', 'Pakan', 'Bibit / Bakalan', 'Obat & Vitamin', 'Peralatan', 'Lainnya'],
      defaultInventoryCategory: 'pakan',
      emptyInventoryDesc: 'Mulai tambahkan pakan konsentrat atau obat hewan ke gudang Anda.',
      stockReceiveNote: 'Penerimaan pakan/obat',
      stockNotePlaceholder: 'Contoh: Konsentrat sapi masuk, Vitamin ternak',
      statsTodayFeed: 'Total konsentrat hari ini',
      statsActiveUnit: 'Kandang aktif',
      statsPop: 'Total ternak',
      statsHarvest: 'Terjual bulan ini',
      btnDetailCycle: 'Detail Ternak',
      btnEditCycle: 'Edit Data',
      modalNewUnitTitle: 'Tambah Kandang / Pen Baru',
      toastUnitSaved: 'Data kandang berhasil disimpan',
      toastUnitDeleted: 'Kandang dihapus',
      unitTabActive: 'Terisi',
      unitTabEmpty: 'Kosong',
      unitTabAll: 'Semua',
      titleUnitMgmt: 'Manajemen Kandang & Pen',
      subUnitMgmt: 'Kelola data kandang, pen individu, dan kapasitas ternak',
      statsTemp: 'Suhu kandang',
      statsO2: 'Kelembaban',
      statsPH: 'Asupan hijauan',
      statsTodayFeedVal: '85.0 kg',
      statsTempVal: '27.8°C',
      statsO2Val: '60 %',
      statsPHVal: 'Optimal',
      totalUnitsLabel: 'Total Kandang',
      warningLabel: 'Pemeriksaan Rutin (Kandang B3)',
      nextFeedLabel: 'Jadwal Pakan & Hijauan',
      nextFeedDetail: 'Konsentrat Sapi Protein Tinggi – 45 Menit lagi',
      tempAvgLabel: 'Suhu Kandang Rata-rata',
      idealConditionLabel: 'Kondisi Optimal Ternak',
      mockA1Title: 'Kandang Blok A1 - Sapi Limosin',
      mockA1Details: 'Usia: 18 Bulan | Populasi: 20 Ekor',
      mockB3Title: 'Kandang Blok B3 - Sapi Brahman',
      mockB3Details: 'Usia: 14 Bulan | Populasi: 15 Ekor',
      mockB3Warning: 'Pengecekan Nafsu Makan',
      mockKPIs: [
        { label: 'Suhu', val: '27.5°C' },
        { label: 'Bobot Rata-rata', val: '450 kg' },
        { label: 'Status', val: 'Sehat' }
      ],
      mockB3KPIs: [
        { label: 'Suhu', val: '29.1°C', alert: true },
        { label: 'Bobot Rata-rata', val: '380 kg' },
        { label: 'Status', val: 'Perhatian', alert: true }
      ],
      alert1Title: 'Pemberian Pakan Selesai',
      alert1Desc: 'Kandang Blok A1 telah diberi ransum konsentrat.',
      alert2Title: 'Jadwal Vitamin Ternak',
      alert2Desc: 'Saatnya pemberian premix vitamin untuk Blok B3.'
    }
  }

  // 3. Sektor Peternakan Unggas / Ayam / Bebek / Puyuh
  const isUnggas = normType === 'unggas' || normType === 'poultry' || normType === 'ayam' || normType === 'bebek' || normType === 'puyuh';
  if (isUnggas) {
    return {
      isTanaman: false,
      category: 'poultry',
      brandName: 'UnggasFarm',
      brandSub: 'Budidaya Pintar',
      brandIcon: 'egg',
      unit: 'Kandang',
      unitLower: 'kandang',
      unitCode: 'Kode Kandang',
      unitName: 'Nama Kandang',
      newUnit: 'Kandang Baru',
      addUnit: 'Tambah Kandang',
      registerUnit: 'Daftarkan Kandang',
      typeUnit: 'Tipe Kandang Unggas',
      types: [
        ['closed_house', 'Closed House (Modern)'],
        ['open_house', 'Open House (Konvensional)'],
        ['semi_closed', 'Semi Closed House'],
        ['baterai', 'Kandang Baterai (Petelur)']
      ],
      selectUnit: 'Pilih Kandang Unggas (Tersedia)',
      noUnitEmpty: '* Tidak ada kandang kosong tersedia saat ini.',
      seedTypeLabel: 'Jenis / Strain DOC (Ayam)',
      seedCountLabel: 'Jumlah Populasi DOC (Ekor)',
      seedCountLabelShort: 'Jumlah DOC / Flock',
      seedDateLabel: 'Tanggal Masuk DOC (Chicking)',
      startCycleLabel: 'Mulai Periode / Siklus Baru',
      startCycleAction: 'Mulai Siklus',
      emptyCyclesDesc: 'Mulai siklus pemeliharaan DOC broiler atau layer pada kandang yang tersedia',
      phLabel: 'Kadar Amonia / FCR',
      tempLabel: 'Suhu Brooding',
      o2Label: 'Sirkulasi & Kelembaban',
      feedLabel: 'Pakan Pur / Starter / Grower',
      feedLabelShort: 'Pakan',
      feedUnit: 'Pakan Pur',
      healthLabel: 'Kesehatan & Program Vaksin',
      populationLabel: 'Kapasitas Flock (Ekor)',
      populationCount: 'ekor',
      populationCountTitle: 'Populasi',
      growthLabel: 'Grafik Pertumbuhan Bobot Ayam (gram)',
      growthSub: 'Kenaikan bobot rata-rata (gram) per minggu',
      growthUnit: 'gram',
      growthMetricLabel: 'Bobot rata-rata',
      activeSeedLabel: 'Unggas / Flock aktif',
      noSeedLabel: 'Belum ada DOC masuk',
      seedGrowthTrend: 'Tren pertumbuhan bobot unggas',
      envCardTitle: 'Kondisi Kandang & Ventilasi',
      envCardIcon: 'air',
      envMainParamLabel: 'Kadar Amonia',
      envMainParamVal: 'Aman (0.02 ppm)',
      envMainStatus: 'Optimal',
      climateCardTitle: 'Suhu & Kelembaban Brooding',
      climateParam1Label: 'Suhu Kandang',
      climateParam1Val: '31.2°C',
      climateParam2Label: 'Kelembaban Udara',
      climateParam2Val: '65%',
      climateTrend: 'Suhu brooding optimal',
      weatherRiskText: 'Risiko suhu turun',
      samplingDesc: 'Sampling dilakukan dengan menimbang bobot sampel ayam secara acak untuk menghitung rata-rata.',
      samplingPlaceholder: 'Contoh: Ayam aktif, sebaran merata, konsumsi pakan baik...',
      healthDiseasePlaceholder: 'Contoh: Gejala ngorok, feses kapur, nafsu makan turun...',
      weatherAdvice: 'Peringatan: Periksa pemanas gas saat cuaca dingin.',
      iconMain: 'egg',
      iconFeed: 'restaurant',
      iconSeed: 'egg',
      iconCycle: 'inventory',
      iconUnitDefault: 'home_work',
      inventoryCategories: ['Semua', 'Pakan', 'Bibit / DOC', 'Vaksin & Obat', 'Peralatan', 'Lainnya'],
      defaultInventoryCategory: 'pakan',
      emptyInventoryDesc: 'Mulai tambahkan pakan pur atau vaksin ke gudang Anda.',
      stockReceiveNote: 'Pakan/DOC masuk',
      stockNotePlaceholder: 'Contoh: Masuk pakan starter, Vaksin ND',
      statsTodayFeed: 'Total pakan hari ini',
      statsActiveUnit: 'Kandang aktif',
      statsPop: 'Total populasi ayam',
      statsHarvest: 'Panen bulan ini',
      btnDetailCycle: 'Detail Siklus',
      btnEditCycle: 'Edit Siklus',
      modalNewUnitTitle: 'Tambah Kandang Baru',
      toastUnitSaved: 'Kandang berhasil disimpan',
      toastUnitDeleted: 'Kandang dihapus',
      unitTabActive: 'Aktif',
      unitTabEmpty: 'Kosong',
      unitTabAll: 'Semua',
      titleUnitMgmt: 'Manajemen Kandang Unggas',
      subUnitMgmt: 'Kelola data kandang dan kapasitas flock',
      statsTemp: 'Suhu kandang',
      statsO2: 'Kelembaban',
      statsPH: 'FCR target',
      statsTodayFeedVal: '145.0 kg',
      statsTempVal: '31.2°C',
      statsO2Val: '65 %',
      statsPHVal: '1.45',
      totalUnitsLabel: 'Total Kandang',
      warningLabel: 'Pemanas Brooding (Kandang B3)',
      nextFeedLabel: 'Jadwal Pakan & Vitamin',
      nextFeedDetail: 'Pur B-11 & Vitamin – 30 Menit lagi',
      tempAvgLabel: 'Suhu Brooding Rata-rata',
      idealConditionLabel: 'Kondisi Ideal Brooding',
      mockA1Title: 'Kandang A1 - Ayam Broiler Super',
      mockA1Details: 'Usia: 28 Hari | Populasi: 3000 Ekor',
      mockB3Title: 'Kandang B3 - Ayam Petelur (Layer)',
      mockB3Details: 'Usia: 120 Hari | Populasi: 1500 Ekor',
      mockB3Warning: 'Suhu Brooding Dingin',
      mockKPIs: [
        { label: 'Suhu', val: '31.5°C' },
        { label: 'FCR', val: '1.42' },
        { label: 'Mortalitas', val: '0.2%' }
      ],
      mockB3KPIs: [
        { label: 'Suhu', val: '28.0°C', alert: true },
        { label: 'FCR', val: '1.65', alert: true },
        { label: 'Mortalitas', val: '0.8%' }
      ],
      alert1Title: 'Siklus Pakan Selesai',
      alert1Desc: 'Kandang A1 telah menerima distribusi pakan sore.',
      alert2Title: 'Peringatan Suhu Brooder',
      alert2Desc: 'Periksa pemanas gas di Kandang B3!'
    }
  }

  // 4. Sektor Burung Kicau & Breeding
  const isBurung = normType === 'burung' || normType === 'bird' || normType === 'lovebird' || normType === 'kenari' || normType === 'murai';
  if (isBurung) {
    return {
      isTanaman: false,
      category: 'bird',
      brandName: 'AviaryPro',
      brandSub: 'Budidaya Pintar',
      brandIcon: 'flutter_dash',
      unit: 'Aviary / Sangkar',
      unitLower: 'aviary',
      unitCode: 'Kode Aviary / Sangkar',
      unitName: 'Nama Sangkar',
      newUnit: 'Aviary Baru',
      addUnit: 'Tambah Aviary',
      registerUnit: 'Daftarkan Sangkar',
      typeUnit: 'Tipe Sangkar',
      types: [
        ['aviary_koloni', 'Aviary Koloni'],
        ['sangkar_ternak', 'Sangkar Box Ternak (Soliter)'],
        ['sangkar_gantung', 'Sangkar Gantung'],
        ['inkubator', 'Mesin Tetas / Handfeed Box']
      ],
      selectUnit: 'Pilih Sangkar (Tersedia)',
      noUnitEmpty: '* Tidak ada sangkar kosong tersedia saat ini.',
      seedTypeLabel: 'Spesies / Mutasi Warna',
      seedCountLabel: 'Jumlah Indukan (Ekor)',
      seedCountLabelShort: 'Jumlah Burung',
      seedDateLabel: 'Tanggal Masuk',
      startCycleLabel: 'Mulai Penjodohan / Breeding',
      startCycleAction: 'Mulai Breeding',
      emptyCyclesDesc: 'Mulai jodohkan burung indukan pada sangkar ternak yang tersedia',
      phLabel: 'Telur Menetas',
      tempLabel: 'Suhu Aviary',
      o2Label: 'Kelembaban',
      feedLabel: 'Biji-bijian & Extra Fooding',
      feedLabelShort: 'Pakan & EF',
      feedUnit: 'Pakan Biji / EF',
      healthLabel: 'Kesehatan Burung & Vitamin',
      populationLabel: 'Kapasitas Sangkar (Ekor)',
      populationCount: 'ekor',
      populationCountTitle: 'Populasi',
      growthLabel: 'Grafik Pertumbuhan Anakan & Tetas',
      growthSub: 'Perkembangan bobot & bulu anakan per minggu',
      growthUnit: 'gram',
      growthMetricLabel: 'Bobot rata-rata',
      activeSeedLabel: 'Pasangan / Indukan aktif',
      noSeedLabel: 'Belum ada indukan terisi',
      seedGrowthTrend: 'Tren perkembangan anakan burung',
      envCardTitle: 'Kondisi Glodok & Sarang',
      envCardIcon: 'nest_cam_indoor',
      envMainParamLabel: 'Kondisi Sarang',
      envMainParamVal: 'Bersih & Kering',
      envMainStatus: 'Optimal',
      climateCardTitle: 'Suhu & Kelembaban Aviary',
      climateParam1Label: 'Suhu Ruang',
      climateParam1Val: '26.8°C',
      climateParam2Label: 'Kelembaban Udara',
      climateParam2Val: '60%',
      climateTrend: 'Suhu optimal pengeraman',
      weatherRiskText: 'Risiko angin kencang',
      samplingDesc: 'Sampling dilakukan dengan memeriksa anakan di glodok dan pemasangan ring kaki.',
      samplingPlaceholder: 'Contoh: Anakan sehat, perkembangan bulu sempurna...',
      healthDiseasePlaceholder: 'Contoh: Bulu mengembang, mata berair, lesu...',
      weatherAdvice: 'Peringatan: Lindungi aviary dari hembusan angin kencang.',
      iconMain: 'flutter_dash',
      iconFeed: 'restaurant',
      iconSeed: 'egg',
      iconCycle: 'inventory',
      iconUnitDefault: 'home_work',
      inventoryCategories: ['Semua', 'Pakan & EF', 'Bibit / Indukan', 'Vitamin & Obat', 'Peralatan & Sangkar', 'Lainnya'],
      defaultInventoryCategory: 'pakan',
      emptyInventoryDesc: 'Mulai tambahkan pakan biji, vitamin, atau ring kaki ke gudang Anda.',
      stockReceiveNote: 'Pakan/Ring masuk',
      stockNotePlaceholder: 'Contoh: Beli milet kiloan, Ring Lovebird',
      statsTodayFeed: 'Total pakan hari ini',
      statsActiveUnit: 'Sangkar terisi',
      statsPop: 'Total burung & anakan',
      statsHarvest: 'Anakan lolos ring bulan ini',
      btnDetailCycle: 'Detail Jodohan',
      btnEditCycle: 'Edit Data',
      modalNewUnitTitle: 'Tambah Aviary / Sangkar Baru',
      toastUnitSaved: 'Sangkar berhasil disimpan',
      toastUnitDeleted: 'Sangkar dihapus',
      unitTabActive: 'Terisi',
      unitTabEmpty: 'Kosong',
      unitTabAll: 'Semua',
      titleUnitMgmt: 'Manajemen Aviary & Sangkar',
      subUnitMgmt: 'Kelola data sangkar breeding dan nomor ring',
      statsTemp: 'Suhu ruang',
      statsO2: 'Kelembaban',
      statsPH: 'Telur inkubasi',
      statsTodayFeedVal: '4.5 kg',
      statsTempVal: '26.8°C',
      statsO2Val: '60 %',
      statsPHVal: '8 Butir',
      totalUnitsLabel: 'Total Sangkar',
      warningLabel: 'Cek Pengeraman (Box 03)',
      nextFeedLabel: 'Jadwal Pakan & EF',
      nextFeedDetail: 'Extra Fooding Jagung Manis & Telur Puyuh – 20 Menit lagi',
      tempAvgLabel: 'Suhu Ruang Aviary',
      idealConditionLabel: 'Kondisi Ideal Breeding',
      mockA1Title: 'Sangkar Box 01 - Lovebird Biola Green',
      mockA1Details: 'Status: Mengeram 4 Butir | Pejantan x Betina',
      mockB3Title: 'Sangkar Box 03 - Murai Batu Medan',
      mockB3Details: 'Status: Siapan Jodoh | 2 Ekor',
      mockB3Warning: 'Periksa Glodok Pengeraman',
      mockKPIs: [
        { label: 'Suhu', val: '27.0°C' },
        { label: 'Telur', val: '4 Butir' },
        { label: 'Fertil', val: '100%' }
      ],
      mockB3KPIs: [
        { label: 'Suhu', val: '28.5°C' },
        { label: 'Telur', val: '2 Butir', alert: true },
        { label: 'Fertil', val: 'Belum Cek' }
      ],
      alert1Title: 'Telur Menetas',
      alert1Desc: '1 butir telur di Sangkar Box 01 telah menetas sempurna!',
      alert2Title: 'Waktunya Pasang Ring',
      alert2Desc: 'Anakan di Box 04 berusia 7 hari, segera pasang ring resmi!'
    }
  }

  // 5. Budidaya Hewan Air / Perikanan (Default: Ikan / Udang)
  return {
    isTanaman: false,
    category: 'aquaculture',
    brandName: 'AquaGrow',
    brandSub: 'Budidaya Pintar',
    brandIcon: 'water_drop',
    unit: 'Kolam',
    unitLower: 'kolam',
    unitCode: 'Kode Kolam',
    unitName: 'Nama Kolam',
    newUnit: 'Kolam Baru',
    addUnit: 'Tambah Kolam',
    registerUnit: 'Daftarkan Kolam',
    typeUnit: 'Jenis Kolam',
    types: [
      ['tanah', 'Tanah'],
      ['beton', 'Beton'],
      ['terpal', 'Terpal'],
      ['bioflok', 'Bioflok']
    ],
    selectUnit: 'Pilih Unit Kolam (Tersedia)',
    noUnitEmpty: '* Tidak ada unit kolam kosong tersedia saat ini.',
    seedTypeLabel: 'Jenis / Varietas Benih',
    seedCountLabel: 'Jumlah Tebar (Ekor)',
    seedCountLabelShort: 'Jumlah Tebar',
    seedDateLabel: 'Tanggal Tebar',
    startCycleLabel: 'Mulai Siklus (Tebar)',
    startCycleAction: 'Mulai Budidaya',
    emptyCyclesDesc: 'Tebar benih di kolam yang kosong untuk memulai monitoring',
    phLabel: 'Tingkat pH',
    tempLabel: 'Suhu',
    o2Label: 'Oksigen Terlarut',
    feedLabel: 'Pakan Pelet',
    feedLabelShort: 'Pakan',
    feedUnit: 'Pakan',
    healthLabel: 'Kesehatan Ikan',
    populationLabel: 'Kapasitas (ekor)',
    populationCount: 'ekor',
    populationCountTitle: 'Populasi',
    growthLabel: 'Grafik Pertumbuhan Ikan',
    growthSub: 'Kenaikan berat rata-rata (gram) per minggu',
    growthUnit: 'gram',
    growthMetricLabel: 'Berat rata-rata',
    activeSeedLabel: 'Ikan aktif',
    noSeedLabel: 'Belum ada ikan',
    seedGrowthTrend: 'Tren pertumbuhan ikan',
    envCardTitle: 'Kualitas Air Kolam',
    envCardIcon: 'waves',
    envMainParamLabel: 'pH Air',
    envMainParamVal: '7.2',
    envMainStatus: 'Optimal',
    climateCardTitle: 'Suhu & DO Kolam',
    climateParam1Label: 'Suhu Air',
    climateParam1Val: '28.5°C',
    climateParam2Label: 'DO (O2)',
    climateParam2Val: '6.4 mg/L',
    climateTrend: 'Stabil 24 jam terakhir',
    weatherRiskText: 'Risiko pH drop',
    samplingDesc: 'Sampling dilakukan dengan menimbang sampel ikan secara acak lalu menghitung berat rata-rata.',
    samplingPlaceholder: 'Contoh: Kondisi ikan sehat, pertumbuhan merata...',
    healthDiseasePlaceholder: 'Contoh: Ikan terlihat lemas, bintik putih...',
    weatherAdvice: 'Peringatan: Matikan pompa pakan otomatis jika hujan lebat untuk mencegah overfeeding.',
    iconMain: 'waves',
    iconFeed: 'restaurant',
    iconSeed: 'water_drop',
    iconCycle: 'set_meal',
    iconUnitDefault: 'water',
    inventoryCategories: ['Semua', 'Pakan', 'Benih & Bibit', 'Obat & Probiotik', 'Peralatan', 'Lainnya'],
    defaultInventoryCategory: 'pakan',
    emptyInventoryDesc: 'Mulai tambahkan pakan pelet atau probiotik ke gudang Anda.',
    stockReceiveNote: 'Penerimaan barang',
    stockNotePlaceholder: 'Contoh: Pembelian pelet baru, Pakan harian',
    statsTodayFeed: 'Total pakan hari ini',
    statsActiveUnit: 'Kolam aktif',
    statsPop: 'Total populasi ikan',
    statsHarvest: 'Panen bulan ini',
    btnDetailCycle: 'Detail Siklus',
    btnEditCycle: 'Edit Siklus',
    modalNewUnitTitle: 'Tambah Kolam Baru',
    toastUnitSaved: 'Kolam berhasil disimpan',
    toastUnitDeleted: 'Kolam dihapus',
    unitTabActive: 'Aktif',
    unitTabEmpty: 'Kosong',
    unitTabAll: 'Semua',
    titleUnitMgmt: 'Manajemen Kolam & Tambak',
    subUnitMgmt: 'Kelola data kolam dan kapasitas tebar',
    statsTemp: 'Suhu air',
    statsO2: 'Oksigen terlarut',
    statsPH: 'Rata-rata pH',
    statsTodayFeedVal: '124.5 kg',
    statsTempVal: '28.4°C',
    statsO2Val: '6.5 mg/L',
    statsPHVal: '7.2',
    totalUnitsLabel: 'Total Kolam',
    warningLabel: 'Kadar Oksigen Rendah (Kolam B3)',
    nextFeedLabel: 'Jadwal Pakan Berikutnya',
    nextFeedDetail: 'Pakan Protein Tinggi – 45 Menit lagi',
    tempAvgLabel: 'Suhu Air Rata-rata',
    idealConditionLabel: 'Kondisi Ideal untuk Nila',
    mockA1Title: 'Kolam A1 - Pembesaran Nila',
    mockA1Details: 'Usia: 45 Hari | Populasi: 2000 Ekor',
    mockB3Title: 'Kolam B3 - Pemijahan Gurame',
    mockB3Details: 'Usia: 12 Hari | Populasi: 500 Ekor',
    mockB3Warning: 'Kadar Oksigen Rendah',
    mockKPIs: [
      { label: 'pH', val: '7.2' },
      { label: 'O2', val: '6.5 mg/L' },
      { label: 'Amoniak', val: '0.01 ppm' }
    ],
    mockB3KPIs: [
      { label: 'pH', val: '6.8' },
      { label: 'O2', val: '3.2 mg/L', alert: true },
      { label: 'Amoniak', val: '0.05 ppm' }
    ],
    alert1Title: 'Penggantian Air Selesai',
    alert1Desc: 'Kolam A1 telah mencapai level target.',
    alert2Title: 'Gagal Pompa Udara',
    alert2Desc: 'Periksa sambungan listrik Kolam B3!'
  }
}

export function useBudidayaTerms() {
  const context = useContext(BudidayaContext)
  if (context && context.terms) {
    return context.terms
  }
  return getBudidayaTerms('ikan')
}
